barebow =  ["Barebow", {
    "Imperial" : ["-","-","-","-"] ,
    "180yd Clout": [" ", " ", " ", " "],
    "180yd Clout (Double)": [" ", " ", " ", " "],
    "Albion": [" ", " ", "Linda Wright", "521"],
    "American": [" ", " ", "Karen Ingram", "324"],
    "American (Double)": [" ", " ", " ", " "],
    "Bray I": [" ", " ", "Linda Wright", "169"],
    "Bray I (Three Spot)": [" ", " ", " ", " "],
    "Bray II": [" ", " ", "Linda Wright", "183"],
    "Bray II (Three Spot)": [" ", " ", " ", " "],
    "Bray Combined": ["Jim Start", "384", "Linda Wright", "353"],
    "Bray Combined (Three Spot)": [" ", " ", " ", " "],
    "Bristol II": [" ", " ", "Linda Wright", "789"],
    "Bristol II (Double)": [" ", " ", " ", " "],
    "Bristol III": [" ", " ", "Linda Wright", "917"],
    "Bristol III (Double)": [" ", " ", " ", " "],
    "Bristol IV": [" ", " ", "Linda Wright", "1020"],
    "Bristol IV (Double)": [" ", " ", " ", " "],
    "Bristol V": [" ", " ", " ", " "],
    "Bristol V (Double)": [" ", " ", " ", " "],
    "Hereford / Bristol I": [" ", " ", "Linda Wright", "668"],
    "Hereford / Bristol I (Double)": [" ", " ", " ", " "],
    "Long National": ["Steven Marsh", "336", "Linda Wright", "270"],
    "Long Warwick": [" ", " ", "Linda Wright", "225"],
    "Long Western": [" ", " ", "Linda Wright", "374"],
    "National": ["Richard Burridge", "492", "Linda Wright", "351"],
    "National 30": [" ", " ", " ", " "],
    "National 40": [" ", " ", "Linda Wright", "439"],
    "National 50": ["John Batten", "454", " ", " "],
    "New National": ["Richard Burridge", "410", " ", " "],
    "New Warwick": [" ", " ", " ", " "],
    "New Western": ["Richard Burridge", "494", " ", " "],
    "Portsmouth (Single Face)": ["Richard Burridge", "568", "Linda Wright", "351"],
    "Portsmouth (Single Face) (Double)": [" ", " ", " ", " "],
    "Portsmouth (Three Spot)": [" ", " ", " ", " "],
    "Portsmouth (Three Spot) (Double)": [" ", " ", " ", " "],
    "St. George": ["Richard Burridge", "667", " ", " "],
    "St. Nicholas": ["Jim Start", "618", "Linda Wright", "546"],
    "Warwick": ["Steven Marsh", "314", "Linda Wright", "267"],
    "Warwick 30": ["Ricky Munt", "350", " ", " "],
    "Warwick 40": [" ", " ", "Linda Wright", "322"],
    "Warwick 50": ["Steven Marsh", "340", " ", " "],
    "Western": ["Richard Burridge", "678", "Linda Wright", "423"],
    "Western 30": [" ", " ", " ", " "],
    "Western 40": [" ", " ", "Linda Wright", "619"],
    "Western 50": [" ", " ", " ", " "],
    "Windsor": ["Steven Marsh", "802", " ", " "],
    "Windsor 30": [" ", " ", " ", " "],
    "Windsor 40": [" ", " ", "Linda Wright", "844"],
    "Windsor 50": [" ", " ", " ", " "],
    "Worcester (Five Spot)": [" ", " ", " ", " "],
    "Worcester (Five Spot) (Double)": [" ", " ", " ", " "],
    "Worcester (Singe Face)": ["Robert 'Pasty' Cain", "236", "Linda Wright", "202"],
    "Worcester (Single Face) (Double)": [" ", " ", " ", " "],
    "York": ["Richard Burridge", "869", " ", " "],
    "York (Double)": [" ", " ", " ", " "],

    "Metric" : ["-","-","-","-"] ,
    "185m Clout": [" ", " ", " ", " "],
    "185m Clout (Double)": [" ", " ", " ", " "],
    "Frostbite": ["Robert 'Pasty' Cain", "	270", "Linda Wright", "245"],
    "Individual Match Round 18m (12 arrows)": ["Richard Burridge", "106", " ", " "],
    "Individual Match Round 50m (15 arrows)": [" ", " ", " ", " "],
    "Long Metric I": [" ", " ", " ", " "],
    "Long Metric II": [" ", " ", " ", " "],
    "Long Metric III": [" ", " ", " ", " "],
    "Long Metric IV": [" ", " ", " ", " "],
    "Long Metric V": [" ", " ", " ", " "],
    "Metric I": [" ", " ", " ", " "],
    "Metric I (Double)": [" ", " ", " ", " "],
    "Metric II": [" ", " ", " ", " "],
    "Metric II (Double)": [" ", " ", " ", " "],
    "Metric III": [" ", " ", " ", " "],
    "Metric III (Double)": [" ", " ", " ", " "],
    "Metric IV": [" ", " ", " ", " "],
    "Metric IV (Double)": [" ", " ", " ", " "],
    "Metric V": [" ", " ", " ", " "],
    "Metric V (Double)": [" ", " ", " ", " "],
    "Short Metric / Short Metric I": [" ", " ", " ", " "],
    "Short Metric II": [" ", " ", " ", " "],
    "Short Metric III": [" ", " ", " ", " "],
    "Short Metric IV": [" ", " ", " ", " "],
    "Short Metric V": [" ", " ", " ", " "],
    "Stafford": [" ", " ", " ", " "],
    "Stafford (Double)": [" ", " ", " ", " "],
    "Three Dozen Metric 30m (80cm face)": ["Richard Burridge", "323", " ", " "],
    "Three Dozen Metric 50m (80cm face)": ["Richard Burridge", "263", " ", " "],
    "Three Dozen Metric 70m (122cm face)": ["Richard Burridge", "241", " ", " "],
    "Three Dozen Metric 90m (122cm face)": ["Richard Burridge", "247", " ", " "],
    "Vegas": ["Robert 'Pasty' Cain", "407", "Linda Wright", "296"],
    "WA Combined (18+25) (Single Face)": ["Richard Burridge", "1080", " ", " "],
    "WA Combined (18+25) (Three Spot)": [" ", " ", " ", " "],
    "WA Field - 24 Target - Marked": [" ", " ", " ", " "],
    "WA Field - 24 Target - Unmarked": [" ", " ", " ", " "],
    "WA Field - Two Day event": [" ", " ", " ", " "],
    "WA Standard Round": [" ", " ", " ", " "],
    "WA Standard Round (Double)": [" ", " ", " ", " "],
    "WA18 (Single Face)": ["Richard Burridge", "533", "Linda Wright", "394"],
    "WA18 (Three Spot)": [" ", " ", " ", " "],
    "WA25 (Single Face)": [" ", " ", "Linda Wright", "382"],
    "WA25 (Three Spot)": [" ", " ", " ", " "],
    "WA50": [" ", " ", " ", " "],
    "WA50 (Double)": [" ", " ", " ", " "],
    "WA60": [" ", " ", " ", " "],
    "WA70": ["Richard Burridge", "510", " ", " "],
    "WA900": [" ", " ", " ", " "],
    "WA1440": ["Richard Burridge", "1047", " ", " "],
    "WA1440 (Double)": [" ", " ", " ", " "]

} ]
