compound =  ["Compound", {
        "Imperial" : ["-","-","-","-"] ,
        "180yd Clout" : [" ", " ", " ", " "] , 
        "180yd Clout (Double)" : [" ", " ", " ", " "] , 
        "Albion" : ["Bob Griffith-Bird", "876", "Vicky Saunders", "896"] , 
        "American" : ["Mike Curtis", "802", "P Hiscox", "634"] , 
        "American (Double)" : [" ", " ", " ", " "] , 
        "Bray I" : ["Marcus Yeoman", "289", "Jackie Hollebon", "240"] , 
        "Bray I (Three Spot)" : [" ", " ", " ", " "] , 
        "Bray II" : ["Bob Griffith-Bird", "293", "P Hiscox", "216"] , 
        "Bray II (Three Spot)" : [" ", " ", " ", " "] ,
        "Bray Combined" : [" ", " ", " ", " "] , 
        "Bray Combined (Three Spot)" : [" ", " ", " ", " "] ,
        "Bristol II" : [" ", " ", "P Nicholson", "1124"] , 
        "Bristol II (Double)" : [" ", " ", " ", " "] , 
        "Bristol III" : [" ", " ", " ", " "] , 
        "Bristol III (Double)" : [" ", " ", " ", " "] , 
        "Bristol IV" : [" ", " ", " ", " "] , 
        "Bristol IV (Double)" : [" ", " ", " ", " "] , 
        "Bristol V" : [" ", " ", " ", " "] , 
        "Bristol V (Double)" : [" ", " ", " ", " "] , 
        "Hereford / Bristol I" : ["Mike Curtis", "1236", "Vicky Saunders", "1188"] , 
        "Hereford / Bristol I (Double)" : [" ", " ", " ", " "] , 
        "Long National" : ["Darren Bennion", "634", "A Bishop", "552"] , 
        "Long Warwick" : ["Darren Bennion", "430", "P Hiscox", "333"] , 
        "Long Western" : ["Mike Curtis", "830", "A Bishop", "720"] , 
        "National" : ["Bob Griffith-Bird", "644", "A Bishop", "578"] , 
        "National 30" : [" ", " ", " ", " "] , 
        "National 40" : [" ", " ", " ", " "] , 
        "National 50" : [" ", " ", "A Rhodes", "433"] , 
        "New National" : ["Darren Bennion", "606", " ", " "] , 
        "New Warwick" : ["Bob Griffith-Bird", "408", " ", " "] , 
        "New Western" : ["Bob Griffith-Bird", "830", " ", " "] , 
        "Portsmouth (Single Face)" : [" ", " ", " ", " "] , 
        "Portsmouth (Single Face) (Double)" : [" ", " ", " ", " "] , 
        "Portsmouth (Three Spot)" : ["Marcus Yeoman", "598", "Vicky Saunders", "558"] , 
        "Portsmouth (Three Spot) (Double)" : ["Marcus Yeoman", "1185", " ", " "] , 
        "St. George" : ["Marcus Yeoman", " ", " ", " "] , 
        "St. Nicholas" : [" ", " ", " ", " "] , 
        "Warwick" : ["Bob Griffith-Bird", "428", " ", " "] , 
        "Warwick 30" : [" ", " ", " ", " "] , 
        "Warwick 40" : [" ", " ", " ", " "] , 
        "Warwick 50" : ["Bob Griffith-Bird", "416", "P Sinclair", "370"] , 
        "Western" : ["Bob Griffith-Bird", "854", "P Hiscox", "720"] , 
        "Western 30" : [" ", " ", " ", " "] , 
        "Western 40" : [" ", " ", " ", " "] , 
        "Western 50" : [" ", " ", " ", " "] , 
        "Windsor" : ["W Mack", "818", "P Hiscox", "746"] , 
        "Windsor 30" : [" ", " ", " ", " "] , 
        "Windsor 40" : [" ", " ", " ", " "] , 
        "Windsor 50" : [" ", " ", " ", " "] , 
        "Worcester (Five Spot)" : ["Marcus Yeoman", "300", " ", " "] , 
        "Worcester (Five Spot) (Double)" : ["Marcus Yeoman", "600", " ", " "] , 
        "Worcester (Singe Face)" : ["Darren Bennion", "300", " ", " "] , 
        "Worcester (Single Face) (Double)" : [" ", " ", "Vicky Saunders", "226"] , 
        "York" : ["Daniel Tompkins", "1254", " ", " "] , 
        "York (Double)" : [" ", " ", " ", " "] , 
        
        "Imperial" : ["-","-","-","-"] ,
        "185m Clout" : [" ", " ", " ", " "] , 
        "185m Clout (Double)" : [" ", " ", " ", " "] , 
        "Frostbite" : [" ", " ", " ", " "] , 
        "Individual Match Round 18m (12 arrows)" : [" ", " ", " ", " "] , 
        "Individual Match Round 50m (15 arrows)" : [" ", " ", " ", " "] , 
        "Long Metric I" : [" ", " ", " ", " "] , 
        "Long Metric II" : [" ", " ", " ", " "] , 
        "Long Metric III" : [" ", " ", " ", " "] , 
        "Long Metric IV" : [" ", " ", " ", " "] , 
        "Long Metric V" : [" ", " ", " ", " "] , 
        "Metric I" : [" ", " ", " ", " "] , 
        "Metric I (Double)" : [" ", " ", " ", " "] , 
        "Metric II" : [" ", " ", " ", " "] , 
        "Metric II (Double)" : [" ", " ", " ", " "] , 
        "Metric III" : [" ", " ", " ", " "] , 
        "Metric III (Double)" : [" ", " ", " ", " "] , 
        "Metric IV" : [" ", " ", " ", " "] , 
        "Metric IV (Double)" : [" ", " ", " ", " "] , 
        "Metric V" : [" ", " ", " ", " "] , 
        "Metric V (Double)" : [" ", " ", " ", " "] , 
        "Short Metric / Short Metric I" : [" ", " ", " ", " "] , 
        "Short Metric II" : [" ", " ", " ", " "] , 
        "Short Metric III" : [" ", " ", " ", " "] , 
        "Short Metric IV" : [" ", " ", " ", " "] , 
        "Short Metric V" : [" ", " ", " ", " "] , 
        "Stafford" : [" ", " ", " ", " "] , 
        "Stafford (Double)" : [" ", " ", " ", " "] , 
        "Three Dozen Metric 30m (80cm face)" : [" ", " ", " ", " "] , 
        "Three Dozen Metric 50m (80cm face)" : [" ", " ", " ", " "] , 
        "Three Dozen Metric 70m (122cm face)" : [" ", " ", " ", " "] , 
        "Three Dozen Metric 90m (122cm face)" : [" ", " ", " ", " "] , 
        "Vegas" : [" ", " ", " ", " "] , 
        "WA Combined (18+25) (Single Face)" : [" ", " ", " ", " "] , 
        "WA Combined (18+25) (Three Spot)" : [" ", " ", " ", " "] , 
        "WA Field - 24 Target - Marked" : [" ", " ", " ", " "] , 
        "WA Field - 24 Target - Unmarked" : [" ", " ", " ", " "] , 
        "WA Field - Two Day event" : [" ", " ", " ", " "] , 
        "WA Standard Round" : [" ", " ", " ", " "] , 
        "WA Standard Round (Double)" : [" ", " ", " ", " "] , 
        "WA18 (Single Face)" : [" ", " ", " ", " "] , 
        "WA18 (Three Spot)" : [" ", " ", " ", " "] , 
        "WA25 (Single Face)" : [" ", " ", " ", " "] , 
        "WA25 (Three Spot)" : [" ", " ", " ", " "] , 
        "WA50" : [" ", " ", " ", " "] , 
        "WA50 (Double)" : [" ", " ", " ", " "] , 
        "WA60" : [" ", " ", " ", " "] , 
        "WA70" : [" ", " ", " ", " "] , 
        "WA900" : [" ", " ", " ", " "] , 
        "WA1440" : [" ", " ", " ", " "] , 
        "WA1440 (Double)" : [" ", " ", " ", " "]
} ]