recurve = {
        "Imperial" : ["-","-","-","-"] ,
        "180yd Clout" : [" ", " ", " ", " "] , 
        "180yd Clout (Double)" : [" ", " ", " ", " "] , 
        "Albion" : [" ", " ", " ", " "] , 
        "American" : [" ", " ", " ", " "] , 
        "American (Double)" : [" ", " ", " ", " "] , 
        "Bray I" : [" ", " ", " ", " "] , 
        "Bray I (Three Spot)" : [" ", " ", " ", " "] , 
        "Bray II" : [" ", " ", " ", " "] , 
        "Bray II (Three Spot)" : [" ", " ", " ", " "] ,
        "Bray Combined" : [" ", " ", " ", " "] , 
        "Bray Combined (Three Spot)" : [" ", " ", " ", " "] ,
        "Bristol II" : [" ", " ", " ", " "] , 
        "Bristol II (Double)" : [" ", " ", " ", " "] , 
        "Bristol III" : [" ", " ", " ", " "] , 
        "Bristol III (Double)" : [" ", " ", " ", " "] , 
        "Bristol IV" : [" ", " ", " ", " "] , 
        "Bristol IV (Double)" : [" ", " ", " ", " "] , 
        "Bristol V" : [" ", " ", " ", " "] , 
        "Bristol V (Double)" : [" ", " ", " ", " "] , 
        "Hereford / Bristol I" : [" ", " ", " ", " "] , 
        "Hereford / Bristol I (Double)" : [" ", " ", " ", " "] , 
        "Long National" : [" ", " ", " ", " "] , 
        "Long Warwick" : [" ", " ", " ", " "] , 
        "Long Western" : [" ", " ", " ", " "] , 
        "National" : [" ", " ", " ", " "] , 
        "National 30" : [" ", " ", " ", " "] , 
        "National 40" : [" ", " ", " ", " "] , 
        "National 50" : [" ", " ", " ", " "] , 
        "New National" : [" ", " ", " ", " "] , 
        "New Warwick" : [" ", " ", " ", " "] , 
        "New Western" : [" ", " ", " ", " "] , 
        "Portsmouth (Single Face)" : [" ", " ", " ", " "] , 
        "Portsmouth (Single Face) (Double)" : [" ", " ", " ", " "] , 
        "Portsmouth (Three Spot)" : [" ", " ", " ", " "] , 
        "Portsmouth (Three Spot) (Double)" : [" ", " ", " ", " "] , 
        "St. George" : [" ", " ", " ", " "] , 
        "St. Nicholas" : [" ", " ", " ", " "] , 
        "Warwick" : [" ", " ", " ", " "] , 
        "Warwick 30" : [" ", " ", " ", " "] , 
        "Warwick 40" : [" ", " ", " ", " "] , 
        "Warwick 50" : [" ", " ", " ", " "] , 
        "Western" : [" ", " ", " ", " "] , 
        "Western 30" : [" ", " ", " ", " "] , 
        "Western 40" : [" ", " ", " ", " "] , 
        "Western 50" : [" ", " ", " ", " "] , 
        "Windsor" : [" ", " ", " ", " "] , 
        "Windsor 30" : [" ", " ", " ", " "] , 
        "Windsor 40" : [" ", " ", " ", " "] , 
        "Windsor 50" : [" ", " ", " ", " "] , 
        "Worcester (Five Spot)" : [" ", " ", " ", " "] , 
        "Worcester (Five Spot) (Double)" : [" ", " ", " ", " "] , 
        "Worcester (Singe Face)" : [" ", " ", " ", " "] , 
        "Worcester (Single Face) (Double)" : [" ", " ", " ", " "] , 
        "York" : [" ", " ", " ", " "] , 
        "York (Double)" : [" ", " ", " ", " "] , 
        
        "Imperial" : ["-","-","-","-"] ,
        "185m Clout" : [" ", " ", " ", " "] , 
        "185m Clout (Double)" : [" ", " ", " ", " "] , 
        "Frostbite" : [" ", " ", " ", " "] , 
        "Individual Match Round 18m (12 arrows)" : [" ", " ", " ", " "] , 
        "Individual Match Round 50m (15 arrows)" : [" ", " ", " ", " "] , 
        "Long Metric I" : [" ", " ", " ", " "] , 
        "Long Metric II" : [" ", " ", " ", " "] , 
        "Long Metric III" : [" ", " ", " ", " "] , 
        "Long Metric IV" : [" ", " ", " ", " "] , 
        "Long Metric V" : [" ", " ", " ", " "] , 
        "Metric I" : [" ", " ", " ", " "] , 
        "Metric I (Double)" : [" ", " ", " ", " "] , 
        "Metric II" : [" ", " ", " ", " "] , 
        "Metric II (Double)" : [" ", " ", " ", " "] , 
        "Metric III" : [" ", " ", " ", " "] , 
        "Metric III (Double)" : [" ", " ", " ", " "] , 
        "Metric IV" : [" ", " ", " ", " "] , 
        "Metric IV (Double)" : [" ", " ", " ", " "] , 
        "Metric V" : [" ", " ", " ", " "] , 
        "Metric V (Double)" : [" ", " ", " ", " "] , 
        "Short Metric / Short Metric I" : [" ", " ", " ", " "] , 
        "Short Metric II" : [" ", " ", " ", " "] , 
        "Short Metric III" : [" ", " ", " ", " "] , 
        "Short Metric IV" : [" ", " ", " ", " "] , 
        "Short Metric V" : [" ", " ", " ", " "] , 
        "Stafford" : [" ", " ", " ", " "] , 
        "Stafford (Double)" : [" ", " ", " ", " "] , 
        "Three Dozen Metric 30m (80cm face)" : [" ", " ", " ", " "] , 
        "Three Dozen Metric 50m (80cm face)" : [" ", " ", " ", " "] , 
        "Three Dozen Metric 70m (122cm face)" : [" ", " ", " ", " "] , 
        "Three Dozen Metric 90m (122cm face)" : [" ", " ", " ", " "] , 
        "Vegas" : [" ", " ", " ", " "] , 
        "WA Combined (18+25) (Single Face)" : [" ", " ", " ", " "] , 
        "WA Combined (18+25) (Three Spot)" : [" ", " ", " ", " "] , 
        "WA Field - 24 Target - Marked" : [" ", " ", " ", " "] , 
        "WA Field - 24 Target - Unmarked" : [" ", " ", " ", " "] , 
        "WA Field - Two Day event" : [" ", " ", " ", " "] , 
        "WA Standard Round" : [" ", " ", " ", " "] , 
        "WA Standard Round (Double)" : [" ", " ", " ", " "] , 
        "WA18 (Single Face)" : [" ", " ", " ", " "] , 
        "WA18 (Three Spot)" : [" ", " ", " ", " "] , 
        "WA25 (Single Face)" : [" ", " ", " ", " "] , 
        "WA25 (Three Spot)" : [" ", " ", " ", " "] , 
        "WA50" : [" ", " ", " ", " "] , 
        "WA50 (Double)" : [" ", " ", " ", " "] , 
        "WA60" : [" ", " ", " ", " "] , 
        "WA70" : [" ", " ", " ", " "] , 
        "WA900" : [" ", " ", " ", " "] , 
        "WA1440" : [" ", " ", " ", " "] , 
        "WA1440 (Double)" : [" ", " ", " ", " "]
}